CC = m68k-amigaos-gcc -m68020
EXE = game

CFLAGS  = -Ofast -fipa-pta -fno-plt -fno-PIC -fno-stack-protector -flto
STRIP = $(HOST)strip

SRC = cd32.c main.c

LDFLAGS = -lc -lgcc -lm -Wl,--as-needed -Wl,--gc-sections -s -flto

OBJ = $(SRC:.c=.o)

all : $(SRC) $(EXE)

$(EXE): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $@ $(LDFLAGS)
	
.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJ) $(EXE) *.iso cdda.raw
